// SPDX-License-Identifier: AGPL-3.0-only
pragma solidity ^0.8.20;

import "forge-std/Script.sol";
import "forge-std/console.sol";

import {OrgDeployer, ITaskManagerBootstrap} from "../../src/OrgDeployer.sol";
import {IHybridVotingInit} from "../../src/libs/ModuleDeploymentLib.sol";
import {RoleConfigStructs} from "../../src/libs/RoleConfigStructs.sol";
import {ModulesFactory} from "../../src/factories/ModulesFactory.sol";
import {UniversalAccountRegistry} from "../../src/UniversalAccountRegistry.sol";

/**
 * @title DeployOrg
 * @notice Deploys a new organization from JSON configuration
 * @dev Reads infrastructure addresses and org config, then deploys via OrgDeployer
 *
 * Usage:
 *   forge script script/DeployOrg.s.sol:DeployOrg \
 *     --rpc-url $RPC_URL \
 *     --broadcast
 *
 * Environment Variables Required:
 *   - ORG_DEPLOYER_ADDRESS: Address of deployed OrgDeployer contract
 *   - GLOBAL_ACCOUNT_REGISTRY: Address of global UniversalAccountRegistry
 *   - ORG_CONFIG_PATH: Path to org config JSON file (default: script/org-config-example.json)
 *   - DEPLOYER_PRIVATE_KEY: Private key for deployment
 */
contract DeployOrg is Script {
    /*═══════════════════════════ STRUCTS ═══════════════════════════*/

    // JSON parsing structs - must match org config JSON structure
    struct OrgConfigJson {
        string orgId;
        string orgName;
        bool autoUpgrade;
        ThresholdConfig threshold;
        RoleConfig[] roles;
        VotingClassConfig[] votingClasses;
        RoleAssignmentsConfig roleAssignments;
        address[] ddInitialTargets;
        bool withPaymaster;
        bool withEducationHub; // Whether to deploy EducationHub (default: true)
        BootstrapConfigJson bootstrap; // Optional: initial projects and tasks
    }

    struct ThresholdConfig {
        uint8 hybrid;
        uint8 directDemocracy;
    }

    struct RoleVouchingConfigJson {
        bool enabled;
        uint32 quorum;
        uint256 voucherRoleIndex;
        bool combineWithHierarchy;
    }

    struct RoleEligibilityDefaultsJson {
        bool eligible;
        bool standing;
    }

    struct RoleHierarchyConfigJson {
        uint256 adminRoleIndex;
    }

    struct RoleDistributionConfigJson {
        bool mintToDeployer;
        address[] additionalWearers;
    }

    struct HatConfigJson {
        uint32 maxSupply;
        bool mutableHat;
    }

    struct RoleConfig {
        string name;
        string image;
        bool canVote;
        RoleVouchingConfigJson vouching;
        RoleEligibilityDefaultsJson defaults;
        RoleHierarchyConfigJson hierarchy;
        RoleDistributionConfigJson distribution;
        HatConfigJson hatConfig;
    }

    struct VotingClassConfig {
        string strategy;
        uint8 slicePct;
        bool quadratic;
        uint256 minBalance;
        address asset;
        uint256[] hatIds;
    }

    struct RoleAssignmentsConfig {
        uint256[] quickJoinRoles;
        uint256[] tokenMemberRoles;
        uint256[] tokenApproverRoles;
        uint256[] taskCreatorRoles;
        uint256[] educationCreatorRoles;
        uint256[] educationMemberRoles;
        uint256[] hybridProposalCreatorRoles;
        uint256[] ddVotingRoles;
        uint256[] ddCreatorRoles;
    }

    // Bootstrap config structs for initial project/task creation
    struct BootstrapProjectConfigJson {
        string title;
        bytes32 metadataHash;
        uint256 cap;
        address[] managers;
        uint256[] createRoles;
        uint256[] claimRoles;
        uint256[] reviewRoles;
        uint256[] assignRoles;
    }

    struct BootstrapTaskConfigJson {
        uint8 projectIndex;
        uint256 payout;
        string title;
        bytes32 metadataHash;
        address bountyToken;
        uint256 bountyPayout;
        bool requiresApplication;
    }

    struct BootstrapConfigJson {
        BootstrapProjectConfigJson[] projects;
        BootstrapTaskConfigJson[] tasks;
    }

    /*═══════════════════════════ MAIN DEPLOYMENT ═══════════════════════════*/

    function run() public {
        // Read infrastructure addresses from JSON file (auto-generated by infrastructure deployment)
        string memory infraJson = vm.readFile("script/config/infrastructure.json");
        address orgDeployerAddr = vm.parseJsonAddress(infraJson, ".orgDeployer");
        address globalAccountRegistry = vm.parseJsonAddress(infraJson, ".globalAccountRegistry");

        require(orgDeployerAddr != address(0), "infrastructure.json not found or invalid - deploy infrastructure first");
        require(globalAccountRegistry != address(0), "infrastructure.json missing globalAccountRegistry");

        // Get org config path (default to example)
        string memory configPath = vm.envOr("ORG_CONFIG_PATH", string("script/config/org-config-example.json"));

        uint256 deployerPrivateKey = vm.envUint("DEPLOYER_PRIVATE_KEY");
        address deployer = vm.addr(deployerPrivateKey);

        console.log("\n=== Starting POA Organization Deployment ===");
        console.log("Deployer:", deployer);
        console.log("OrgDeployer:", orgDeployerAddr);
        console.log("GlobalAccountRegistry:", globalAccountRegistry);
        console.log("Config Path:", configPath);

        // Read and parse org config
        string memory configJson = vm.readFile(configPath);
        OrgConfigJson memory config = _parseOrgConfig(configJson);

        console.log("\nOrganization Config:");
        console.log("  ID:", config.orgId);
        console.log("  Name:", config.orgName);
        console.log("  Auto Upgrade:", config.autoUpgrade);
        console.log("  Roles:", config.roles.length);
        console.log("  Voting Classes:", config.votingClasses.length);

        // Build deployment params (deployer will receive ADMIN hat)
        OrgDeployer.DeploymentParams memory params = _buildDeploymentParams(config, globalAccountRegistry, deployer);

        // Deploy organization
        vm.startBroadcast(deployerPrivateKey);

        OrgDeployer orgDeployer = OrgDeployer(orgDeployerAddr);

        OrgDeployer.DeploymentResult memory result;

        if (config.withPaymaster) {
            console.log("\nDeploying org WITH paymaster...");
            // Note: Paymaster deployment requires additional bytecode parameter
            // For now, deploy without paymaster. Add paymaster support as needed.
            result = orgDeployer.deployFullOrg(params);
            console.log("Warning: Paymaster deployment not yet implemented in script");
        } else {
            console.log("\nDeploying org...");
            result = orgDeployer.deployFullOrg(params);
        }

        // Register deployer username on GlobalAccountRegistry
        string memory deployerUsername = vm.envOr("DEPLOYER_USERNAME", string("hudsonhrh"));
        if (bytes(deployerUsername).length > 0) {
            UniversalAccountRegistry globalReg = UniversalAccountRegistry(globalAccountRegistry);
            if (bytes(globalReg.getUsername(deployer)).length == 0) {
                globalReg.registerAccount(deployerUsername);
                console.log("Deployer registered as:", deployerUsername);
            }
        }

        vm.stopBroadcast();

        // Output deployment results
        _outputDeployment(config, result);

        console.log("\n=== Organization Deployment Complete ===\n");
    }

    /*═══════════════════════════ CONFIG PARSING ═══════════════════════════*/

    function _parseOrgConfig(string memory configJson) internal returns (OrgConfigJson memory config) {
        // Parse top-level fields
        config.orgId = vm.parseJsonString(configJson, ".orgId");
        config.orgName = vm.parseJsonString(configJson, ".orgName");
        config.autoUpgrade = vm.parseJsonBool(configJson, ".autoUpgrade");
        config.withPaymaster = vm.parseJsonBool(configJson, ".withPaymaster");

        // Parse withEducationHub (default to true for backward compatibility)
        try vm.parseJsonBool(configJson, ".withEducationHub") returns (bool withEduHub) {
            config.withEducationHub = withEduHub;
        } catch {
            config.withEducationHub = true; // Default to enabled for backward compatibility
        }

        // Parse threshold
        config.threshold.hybrid = uint8(vm.parseJsonUint(configJson, ".threshold.hybrid"));
        config.threshold.directDemocracy = uint8(vm.parseJsonUint(configJson, ".threshold.directDemocracy"));

        // Parse roles array - use serializeJson to work around struct array limitations
        // First, manually count by trying to parse until we fail (reasonable max: 100)
        uint256 rolesLength = 0;
        for (uint256 i = 0; i < 100; i++) {
            try vm.parseJsonString(configJson, string.concat(".roles[", vm.toString(i), "].name")) returns (
                string memory
            ) {
                rolesLength++;
            } catch {
                break;
            }
        }

        config.roles = new RoleConfig[](rolesLength);
        for (uint256 i = 0; i < rolesLength; i++) {
            string memory basePath = string.concat(".roles[", vm.toString(i), "]");
            config.roles[i].name = vm.parseJsonString(configJson, string.concat(basePath, ".name"));
            config.roles[i].image = vm.parseJsonString(configJson, string.concat(basePath, ".image"));
            config.roles[i].canVote = vm.parseJsonBool(configJson, string.concat(basePath, ".canVote"));

            // Parse nested vouching config (optional - use try/catch for backwards compat)
            try vm.parseJsonBool(configJson, string.concat(basePath, ".vouching.enabled")) returns (bool enabled) {
                config.roles[i].vouching.enabled = enabled;
                config.roles[i].vouching.quorum =
                    uint32(vm.parseJsonUint(configJson, string.concat(basePath, ".vouching.quorum")));
                config.roles[i].vouching.voucherRoleIndex =
                    vm.parseJsonUint(configJson, string.concat(basePath, ".vouching.voucherRoleIndex"));
                config.roles[i].vouching.combineWithHierarchy =
                    vm.parseJsonBool(configJson, string.concat(basePath, ".vouching.combineWithHierarchy"));
            } catch {}

            // Parse nested defaults config (optional)
            try vm.parseJsonBool(configJson, string.concat(basePath, ".defaults.eligible")) returns (bool eligible) {
                config.roles[i].defaults.eligible = eligible;
                config.roles[i].defaults.standing =
                    vm.parseJsonBool(configJson, string.concat(basePath, ".defaults.standing"));
            } catch {
                // Default to eligible=true, standing=true for backwards compat
                config.roles[i].defaults.eligible = true;
                config.roles[i].defaults.standing = true;
            }

            // Parse nested hierarchy config (optional)
            try vm.parseJsonUint(configJson, string.concat(basePath, ".hierarchy.adminRoleIndex")) returns (
                uint256 adminIdx
            ) {
                config.roles[i].hierarchy.adminRoleIndex = adminIdx;
            } catch {
                // Default to type(uint256).max for backwards compat
                config.roles[i].hierarchy.adminRoleIndex = type(uint256).max;
            }

            // Parse nested distribution config (optional)
            try vm.parseJsonBool(configJson, string.concat(basePath, ".distribution.mintToDeployer")) returns (
                bool mintToDeployer
            ) {
                config.roles[i].distribution.mintToDeployer = mintToDeployer;
                bytes memory additionalWearersData =
                    vm.parseJson(configJson, string.concat(basePath, ".distribution.additionalWearers"));
                config.roles[i].distribution.additionalWearers = abi.decode(additionalWearersData, (address[]));
            } catch {}

            // Parse nested hatConfig (optional)
            try vm.parseJsonUint(configJson, string.concat(basePath, ".hatConfig.maxSupply")) returns (
                uint256 maxSupply
            ) {
                config.roles[i].hatConfig.maxSupply = uint32(maxSupply);
                config.roles[i].hatConfig.mutableHat =
                    vm.parseJsonBool(configJson, string.concat(basePath, ".hatConfig.mutableHat"));
            } catch {
                // Default to unlimited and mutable for backwards compat
                config.roles[i].hatConfig.maxSupply = type(uint32).max;
                config.roles[i].hatConfig.mutableHat = true;
            }
        }

        // Parse voting classes array (reasonable max: 100)
        uint256 votingClassesLength = 0;
        for (uint256 i = 0; i < 100; i++) {
            try vm.parseJsonString(configJson, string.concat(".votingClasses[", vm.toString(i), "].strategy")) returns (
                string memory
            ) {
                votingClassesLength++;
            } catch {
                break;
            }
        }

        config.votingClasses = new VotingClassConfig[](votingClassesLength);
        for (uint256 i = 0; i < votingClassesLength; i++) {
            string memory basePath = string.concat(".votingClasses[", vm.toString(i), "]");
            config.votingClasses[i].strategy = vm.parseJsonString(configJson, string.concat(basePath, ".strategy"));
            config.votingClasses[i].slicePct = uint8(vm.parseJsonUint(configJson, string.concat(basePath, ".slicePct")));
            config.votingClasses[i].quadratic = vm.parseJsonBool(configJson, string.concat(basePath, ".quadratic"));
            config.votingClasses[i].minBalance = vm.parseJsonUint(configJson, string.concat(basePath, ".minBalance"));
            config.votingClasses[i].asset = vm.parseJsonAddress(configJson, string.concat(basePath, ".asset"));

            // Parse hatIds array
            bytes memory hatIdsData = vm.parseJson(configJson, string.concat(basePath, ".hatIds"));
            config.votingClasses[i].hatIds = abi.decode(hatIdsData, (uint256[]));
        }

        // Parse role assignments
        bytes memory quickJoinData = vm.parseJson(configJson, ".roleAssignments.quickJoinRoles");
        config.roleAssignments.quickJoinRoles = abi.decode(quickJoinData, (uint256[]));

        bytes memory tokenMemberData = vm.parseJson(configJson, ".roleAssignments.tokenMemberRoles");
        config.roleAssignments.tokenMemberRoles = abi.decode(tokenMemberData, (uint256[]));

        bytes memory tokenApproverData = vm.parseJson(configJson, ".roleAssignments.tokenApproverRoles");
        config.roleAssignments.tokenApproverRoles = abi.decode(tokenApproverData, (uint256[]));

        bytes memory taskCreatorData = vm.parseJson(configJson, ".roleAssignments.taskCreatorRoles");
        config.roleAssignments.taskCreatorRoles = abi.decode(taskCreatorData, (uint256[]));

        bytes memory educationCreatorData = vm.parseJson(configJson, ".roleAssignments.educationCreatorRoles");
        config.roleAssignments.educationCreatorRoles = abi.decode(educationCreatorData, (uint256[]));

        bytes memory educationMemberData = vm.parseJson(configJson, ".roleAssignments.educationMemberRoles");
        config.roleAssignments.educationMemberRoles = abi.decode(educationMemberData, (uint256[]));

        bytes memory hybridProposalData = vm.parseJson(configJson, ".roleAssignments.hybridProposalCreatorRoles");
        config.roleAssignments.hybridProposalCreatorRoles = abi.decode(hybridProposalData, (uint256[]));

        bytes memory ddVotingData = vm.parseJson(configJson, ".roleAssignments.ddVotingRoles");
        config.roleAssignments.ddVotingRoles = abi.decode(ddVotingData, (uint256[]));

        bytes memory ddCreatorData = vm.parseJson(configJson, ".roleAssignments.ddCreatorRoles");
        config.roleAssignments.ddCreatorRoles = abi.decode(ddCreatorData, (uint256[]));

        // Parse DD initial targets
        bytes memory ddTargetsData = vm.parseJson(configJson, ".ddInitialTargets");
        config.ddInitialTargets = abi.decode(ddTargetsData, (address[]));

        // Parse bootstrap config (optional)
        config.bootstrap = _parseBootstrapConfig(configJson);

        return config;
    }

    function _parseBootstrapConfig(string memory configJson) internal returns (BootstrapConfigJson memory bootstrap) {
        // Count bootstrap projects
        uint256 projectsLength = 0;
        for (uint256 i = 0; i < 100; i++) {
            try vm.parseJsonString(
                configJson, string.concat(".bootstrap.projects[", vm.toString(i), "].title")
            ) returns (
                string memory
            ) {
                projectsLength++;
            } catch {
                break;
            }
        }

        if (projectsLength == 0) {
            return bootstrap; // No bootstrap config
        }

        bootstrap.projects = new BootstrapProjectConfigJson[](projectsLength);
        for (uint256 i = 0; i < projectsLength; i++) {
            string memory basePath = string.concat(".bootstrap.projects[", vm.toString(i), "]");

            bootstrap.projects[i].title = vm.parseJsonString(configJson, string.concat(basePath, ".title"));

            // Parse metadataHash (optional, default to 0)
            try vm.parseJsonBytes32(configJson, string.concat(basePath, ".metadataHash")) returns (bytes32 hash) {
                bootstrap.projects[i].metadataHash = hash;
            } catch {
                bootstrap.projects[i].metadataHash = bytes32(0);
            }

            bootstrap.projects[i].cap = vm.parseJsonUint(configJson, string.concat(basePath, ".cap"));

            // Parse managers array (optional)
            try vm.parseJson(configJson, string.concat(basePath, ".managers")) returns (bytes memory managersData) {
                bootstrap.projects[i].managers = abi.decode(managersData, (address[]));
            } catch {
                bootstrap.projects[i].managers = new address[](0);
            }

            // Parse role arrays
            bytes memory createRolesData = vm.parseJson(configJson, string.concat(basePath, ".createRoles"));
            bootstrap.projects[i].createRoles = abi.decode(createRolesData, (uint256[]));

            bytes memory claimRolesData = vm.parseJson(configJson, string.concat(basePath, ".claimRoles"));
            bootstrap.projects[i].claimRoles = abi.decode(claimRolesData, (uint256[]));

            bytes memory reviewRolesData = vm.parseJson(configJson, string.concat(basePath, ".reviewRoles"));
            bootstrap.projects[i].reviewRoles = abi.decode(reviewRolesData, (uint256[]));

            bytes memory assignRolesData = vm.parseJson(configJson, string.concat(basePath, ".assignRoles"));
            bootstrap.projects[i].assignRoles = abi.decode(assignRolesData, (uint256[]));
        }

        // Count bootstrap tasks
        uint256 tasksLength = 0;
        for (uint256 i = 0; i < 100; i++) {
            try vm.parseJsonString(configJson, string.concat(".bootstrap.tasks[", vm.toString(i), "].title")) returns (
                string memory
            ) {
                tasksLength++;
            } catch {
                break;
            }
        }

        bootstrap.tasks = new BootstrapTaskConfigJson[](tasksLength);
        for (uint256 i = 0; i < tasksLength; i++) {
            string memory basePath = string.concat(".bootstrap.tasks[", vm.toString(i), "]");

            bootstrap.tasks[i].projectIndex =
                uint8(vm.parseJsonUint(configJson, string.concat(basePath, ".projectIndex")));
            bootstrap.tasks[i].payout = vm.parseJsonUint(configJson, string.concat(basePath, ".payout"));
            bootstrap.tasks[i].title = vm.parseJsonString(configJson, string.concat(basePath, ".title"));

            // Parse metadataHash (optional, default to 0)
            try vm.parseJsonBytes32(configJson, string.concat(basePath, ".metadataHash")) returns (bytes32 hash) {
                bootstrap.tasks[i].metadataHash = hash;
            } catch {
                bootstrap.tasks[i].metadataHash = bytes32(0);
            }

            bootstrap.tasks[i].bountyToken = vm.parseJsonAddress(configJson, string.concat(basePath, ".bountyToken"));
            bootstrap.tasks[i].bountyPayout = vm.parseJsonUint(configJson, string.concat(basePath, ".bountyPayout"));
            bootstrap.tasks[i].requiresApplication =
                vm.parseJsonBool(configJson, string.concat(basePath, ".requiresApplication"));
        }

        return bootstrap;
    }

    /*═══════════════════════════ PARAM BUILDING ═══════════════════════════*/

    /**
     * @notice Convert array of role indices to bitmap
     * @dev Each bit represents a role index (bit N = role N)
     * @param roles Array of role indices
     * @return bitmap Bitmap representation where bit N is set if role N is in array
     */
    function _roleArrayToBitmap(uint256[] memory roles) internal pure returns (uint256 bitmap) {
        for (uint256 i = 0; i < roles.length; i++) {
            require(roles[i] < 256, "Role index must be < 256");
            bitmap |= (1 << roles[i]);
        }
    }

    function _buildDeploymentParams(OrgConfigJson memory config, address globalAccountRegistry, address deployerAddress)
        internal
        view
        returns (OrgDeployer.DeploymentParams memory params)
    {
        // Set basic params
        params.orgId = keccak256(bytes(config.orgId));
        params.orgName = config.orgName;
        params.metadataHash = bytes32(0); // No metadata hash by default (can be set via env)
        params.registryAddr = globalAccountRegistry;
        params.deployerAddress = deployerAddress; // Address to receive ADMIN hat
        params.deployerUsername = vm.envOr("DEPLOYER_USERNAME", string("hudsonhrh"));
        params.autoUpgrade = config.autoUpgrade;
        params.hybridThresholdPct = config.threshold.hybrid;
        params.ddThresholdPct = config.threshold.directDemocracy;
        params.ddInitialTargets = config.ddInitialTargets;

        // Build role configs
        params.roles = new RoleConfigStructs.RoleConfig[](config.roles.length);

        for (uint256 i = 0; i < config.roles.length; i++) {
            RoleConfig memory role = config.roles[i];

            params.roles[i] = RoleConfigStructs.RoleConfig({
                name: role.name,
                image: role.image,
                metadataCID: bytes32(0), // TODO: Add to JSON config when needed
                canVote: role.canVote,
                vouching: RoleConfigStructs.RoleVouchingConfig({
                    enabled: role.vouching.enabled,
                    quorum: role.vouching.quorum,
                    voucherRoleIndex: role.vouching.voucherRoleIndex,
                    combineWithHierarchy: role.vouching.combineWithHierarchy
                }),
                defaults: RoleConfigStructs.RoleEligibilityDefaults({
                    eligible: role.defaults.eligible, standing: role.defaults.standing
                }),
                hierarchy: RoleConfigStructs.RoleHierarchyConfig({adminRoleIndex: role.hierarchy.adminRoleIndex}),
                distribution: RoleConfigStructs.RoleDistributionConfig({
                    mintToDeployer: role.distribution.mintToDeployer,
                    additionalWearers: role.distribution.additionalWearers
                }),
                hatConfig: RoleConfigStructs.HatConfig({
                    maxSupply: role.hatConfig.maxSupply, mutableHat: role.hatConfig.mutableHat
                })
            });
        }

        // Build voting classes
        params.hybridClasses = new IHybridVotingInit.ClassConfig[](config.votingClasses.length);

        for (uint256 i = 0; i < config.votingClasses.length; i++) {
            VotingClassConfig memory vClass = config.votingClasses[i];

            IHybridVotingInit.ClassStrategy strategy;
            if (keccak256(bytes(vClass.strategy)) == keccak256(bytes("DIRECT"))) {
                strategy = IHybridVotingInit.ClassStrategy.DIRECT;
            } else if (keccak256(bytes(vClass.strategy)) == keccak256(bytes("ERC20_BAL"))) {
                strategy = IHybridVotingInit.ClassStrategy.ERC20_BAL;
            } else {
                revert("Invalid strategy: must be DIRECT or ERC20_BAL");
            }

            params.hybridClasses[i] = IHybridVotingInit.ClassConfig({
                strategy: strategy,
                slicePct: vClass.slicePct,
                quadratic: vClass.quadratic,
                minBalance: vClass.minBalance,
                asset: vClass.asset,
                hatId: vClass.hatIds.length > 0 ? vClass.hatIds[0] : 0
            });
        }

        // Build role assignments (convert arrays to bitmaps)
        params.roleAssignments = OrgDeployer.RoleAssignments({
            quickJoinRolesBitmap: _roleArrayToBitmap(config.roleAssignments.quickJoinRoles),
            tokenMemberRolesBitmap: _roleArrayToBitmap(config.roleAssignments.tokenMemberRoles),
            tokenApproverRolesBitmap: _roleArrayToBitmap(config.roleAssignments.tokenApproverRoles),
            taskCreatorRolesBitmap: _roleArrayToBitmap(config.roleAssignments.taskCreatorRoles),
            educationCreatorRolesBitmap: _roleArrayToBitmap(config.roleAssignments.educationCreatorRoles),
            educationMemberRolesBitmap: _roleArrayToBitmap(config.roleAssignments.educationMemberRoles),
            hybridProposalCreatorRolesBitmap: _roleArrayToBitmap(config.roleAssignments.hybridProposalCreatorRoles),
            ddVotingRolesBitmap: _roleArrayToBitmap(config.roleAssignments.ddVotingRoles),
            ddCreatorRolesBitmap: _roleArrayToBitmap(config.roleAssignments.ddCreatorRoles)
        });

        // Metadata admin role index (type(uint256).max = skip, use topHat fallback)
        params.metadataAdminRoleIndex = type(uint256).max;

        // Build education hub config
        params.educationHubConfig = ModulesFactory.EducationHubConfig({enabled: config.withEducationHub});

        // Build bootstrap config for initial projects/tasks
        params.bootstrap = _buildBootstrapConfig(config.bootstrap);

        // Default paymaster config (no auto-whitelist, no fee caps, skip operator role)
        params.paymasterConfig = OrgDeployer.PaymasterConfig({
            operatorRoleIndex: type(uint256).max,
            autoWhitelistContracts: false,
            maxFeePerGas: 0,
            maxPriorityFeePerGas: 0,
            maxCallGas: 0,
            maxVerificationGas: 0,
            maxPreVerificationGas: 0,
            defaultBudgetCapPerEpoch: 0,
            defaultBudgetEpochLen: 0
        });

        return params;
    }

    function _buildBootstrapConfig(BootstrapConfigJson memory bootstrapJson)
        internal
        pure
        returns (OrgDeployer.BootstrapConfig memory bootstrap)
    {
        if (bootstrapJson.projects.length == 0) {
            return bootstrap; // Empty bootstrap
        }

        // Build project configs.
        //
        // Bootstrap JSON still encodes per-cap allowlists as role-index arrays (e.g. [0,1,2]).
        // Under the capability-hat refactor each cap is a single hat, so we pick the first
        // role index from each array. OrgDeployer._resolveBootstrapHatIndex then translates
        // role index → hat ID at deploy time using the freshly-created roleHatIds.
        //
        // Sentinel `type(uint256).max` = "no project-level override" (TaskManager falls
        // back to the global cap hat). An empty role array in JSON maps to that sentinel.
        bootstrap.projects = new ITaskManagerBootstrap.BootstrapProjectConfig[](bootstrapJson.projects.length);
        for (uint256 i = 0; i < bootstrapJson.projects.length; i++) {
            bootstrap.projects[i] = ITaskManagerBootstrap.BootstrapProjectConfig({
                title: bytes(bootstrapJson.projects[i].title),
                metadataHash: bootstrapJson.projects[i].metadataHash,
                cap: bootstrapJson.projects[i].cap,
                managers: bootstrapJson.projects[i].managers,
                createHat: bootstrapJson.projects[i].createRoles.length > 0
                    ? bootstrapJson.projects[i].createRoles[0]
                    : type(uint256).max,
                claimHat: bootstrapJson.projects[i].claimRoles.length > 0
                    ? bootstrapJson.projects[i].claimRoles[0]
                    : type(uint256).max,
                reviewHat: bootstrapJson.projects[i].reviewRoles.length > 0
                    ? bootstrapJson.projects[i].reviewRoles[0]
                    : type(uint256).max,
                assignHat: bootstrapJson.projects[i].assignRoles.length > 0
                    ? bootstrapJson.projects[i].assignRoles[0]
                    : type(uint256).max,
                bountyTokens: new address[](0),
                bountyCaps: new uint256[](0)
            });
        }

        // Build task configs
        bootstrap.tasks = new ITaskManagerBootstrap.BootstrapTaskConfig[](bootstrapJson.tasks.length);
        for (uint256 i = 0; i < bootstrapJson.tasks.length; i++) {
            bootstrap.tasks[i] = ITaskManagerBootstrap.BootstrapTaskConfig({
                projectIndex: bootstrapJson.tasks[i].projectIndex,
                payout: bootstrapJson.tasks[i].payout,
                title: bytes(bootstrapJson.tasks[i].title),
                metadataHash: bootstrapJson.tasks[i].metadataHash,
                bountyToken: bootstrapJson.tasks[i].bountyToken,
                bountyPayout: bootstrapJson.tasks[i].bountyPayout,
                requiresApplication: bootstrapJson.tasks[i].requiresApplication
            });
        }

        return bootstrap;
    }

    /*═══════════════════════════ OUTPUT ═══════════════════════════*/

    function _outputDeployment(OrgConfigJson memory config, OrgDeployer.DeploymentResult memory result) internal view {
        console.log("\n--- Deployed Organization Addresses ---");
        console.log("{");
        console.log('  "orgId": "%s",', config.orgId);
        console.log('  "orgName": "%s",', config.orgName);
        console.log('  "contracts": {');
        console.log('    "executor": "%s",', result.executor);
        console.log('    "hybridVoting": "%s",', result.hybridVoting);
        console.log('    "directDemocracyVoting": "%s",', result.directDemocracyVoting);
        console.log('    "quickJoin": "%s",', result.quickJoin);
        console.log('    "participationToken": "%s",', result.participationToken);
        console.log('    "taskManager": "%s",', result.taskManager);
        console.log('    "educationHub": "%s",', result.educationHub);
        console.log('    "paymentManager": "%s"', result.paymentManager);
        console.log("  }");
        console.log("}");
    }
}
